/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Ports_constants.h"



const PortsConstants g_Ports_constants;

PortsConstants::PortsConstants() {
  basePort = 9090LL;

  matUtilPortOffset = 0LL;

  features2DPortOffset = 1LL;

}



