/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Features2D_CONSTANTS_H
#define Features2D_CONSTANTS_H

#include "OpenCV/Features2D/Features2D_types.h"



class Features2DConstants {
 public:
  Features2DConstants();

};

extern const Features2DConstants g_Features2D_constants;



#endif
