/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Ports_CONSTANTS_H
#define Ports_CONSTANTS_H

#include "Ports_types.h"



class PortsConstants {
 public:
  PortsConstants();

  int64_t basePort;
  int64_t matUtilPortOffset;
  int64_t features2DPortOffset;
};

extern const PortsConstants g_Ports_constants;



#endif
