/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CVDef_TYPES_H
#define CVDef_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




struct CVType {
  enum type {
    T8UC1 = 0,
    T8UC2 = 1,
    T8UC3 = 2,
    T8UC4 = 3,
    T8SC1 = 4,
    T8SC2 = 5,
    T8SC3 = 6,
    T8SC4 = 7,
    T16UC1 = 8,
    T16UC2 = 9,
    T16UC3 = 10,
    T16UC4 = 11,
    T16SC1 = 12,
    T16SC2 = 13,
    T16SC3 = 14,
    T16SC4 = 15,
    T32SC1 = 16,
    T32SC2 = 17,
    T32SC3 = 18,
    T32SC4 = 19,
    T32FC1 = 20,
    T32FC2 = 21,
    T32FC3 = 22,
    T32FC4 = 23,
    T64FC1 = 24,
    T64FC2 = 25,
    T64FC3 = 26,
    T64FC4 = 27
  };
};

extern const std::map<int, const char*> _CVType_VALUES_TO_NAMES;



#endif
