/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OpenCVThrift/OpenCV/Core/CVDef_constants.h"



const CVDefConstants g_CVDef_constants;

CVDefConstants::CVDefConstants() {
}



