/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Mat_CONSTANTS_H
#define Mat_CONSTANTS_H

#include "OpenCV/Core/Mat_types.h"



class MatConstants {
 public:
  MatConstants();

};

extern const MatConstants g_Mat_constants;



#endif
