/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OpenCV/Core/MatUtil_constants.h"



const MatUtilConstants g_MatUtil_constants;

MatUtilConstants::MatUtilConstants() {
}



