/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MatUtil_CONSTANTS_H
#define MatUtil_CONSTANTS_H

#include "OpenCV/Core/MatUtil_types.h"



class MatUtilConstants {
 public:
  MatUtilConstants();

};

extern const MatUtilConstants g_MatUtil_constants;



#endif
