/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Types_CONSTANTS_H
#define Types_CONSTANTS_H

#include "OpenCV/Core/Types_types.h"



class TypesConstants {
 public:
  TypesConstants();

};

extern const TypesConstants g_Types_constants;



#endif
