/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "OpenCV/Features2D/Features2D_constants.h"



const Features2DConstants g_Features2D_constants;

Features2DConstants::Features2DConstants() {
}



