/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "modules/core/gen-cpp/mat_constants.h"



const matConstants g_mat_constants;

matConstants::matConstants() {
}



