/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mat_CONSTANTS_H
#define mat_CONSTANTS_H

#include "mat_types.h"

namespace opencv {

class matConstants {
 public:
  matConstants();

};

extern const matConstants g_mat_constants;

} // namespace

#endif
