/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CVDef_CONSTANTS_H
#define CVDef_CONSTANTS_H

#include "OpenCVThrift/OpenCV/Core/CVDef_types.h"



class CVDefConstants {
 public:
  CVDefConstants();

};

extern const CVDefConstants g_CVDef_constants;



#endif
